### ISSUE TITLE
转载申请

### ISSUE THREAD

**Issue by ItsukaRilu** [taroxd/n8440fe#132]
taroxd大大你好，我看完这本轻小说觉得您的翻译质量非常高，在此申请将您翻译的文本制作成epub转载至lk（轻之国度）epub区给更多人看到，希望能够得到授权。

**Comment by Catkamakura** [comment]
lk有这本书啊，也有ePub来着

**Comment by ItsukaRilu** [comment]
噢，之前没看到，谢谢提醒
