### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by AidenOfficial** [taroxd/n8440fe#133]
先谢谢汉化组的无偿付出，翻译这么精良信达雅的汉化很少见了
然后催更催更催更

**Comment by taroxd** [comment]
催作者去

**Comment by MasterOfStar** [comment]
现在翻译进度==更新进度
所以只能等作者写出来咯

**Comment by YukiWong9** [comment]
追影鸽快更新冷娇（错email）

在 2021年1月22日週五 下午12:11，MasterOfStar <notifications@github.com> 寫道：
