### ISSUE TITLE
一些错别字

### ISSUE THREAD

**Issue by Gompyn** [taroxd/n8440fe#2]
- "比赛"→"鼻塞".
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0002.tex#L17

- "哪里"→"那里".
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0002.tex#L129

- "的"→"地".
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0002.tex#L141
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0003.tex#L147
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0006.tex#L121
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0008.tex#L51
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0011.tex#L75
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0024.tex#L76
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0026.tex#L209
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0028.tex#L85
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0029.tex#L43
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0039.tex#L91
"一脸无奈的"→"一脸无奈地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0004.tex#L39
"七七八八的"→"七七八八地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0005.tex#L69
"理所当然的"→"理所当然地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0006.tex#L45
"微妙的"→"微妙地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0010.tex#L7
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0024.tex#L80
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0035.tex#L41
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0036.tex#L119
"十分的"→"十分地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0010.tex#L69
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0018.tex#L39
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0026.tex#L91
"非常的"→"非常地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0010.tex#L71
"毫不客气的"→"毫不客气地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0010.tex#L85
"格外的"→"格外地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0011.tex#L119
"相对的"→"相对地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0011.tex#L143
"这个那个的"→"这个那个地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0012.tex#L85
"几分烦躁的"→"几分烦躁地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0012.tex#L103
"单纯的"→"单纯地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0012.tex#L195
"想入非非的"→"想入非非地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0012.tex#L199
"如此的"→"如此地"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0017.tex#L155
"本能的"→"本能地"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0019.tex#L111
"相当的"→"相当地"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0020.tex#L207
"肉眼可见的"→"肉眼可见地"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0023.tex#L99
"非常的"→"非常地"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0030.tex#L73
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0037.tex#L175
"更多的"→"更多地"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0033.tex#L53
"莫名的"→"莫名地"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0033.tex#L133
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0036.tex#L119
"过多的"→"过多地"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0034.tex#L127
"略微的"→"略微地"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0039.tex#L99

- "舀了一勺周"→"舀了一勺粥"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0003.tex#L185

**Comment by Gompyn** [comment]
- "的"→"得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0011.tex#L127
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0015.tex#L39
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0015.tex#L45
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0015.tex#L49
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0017.tex#L77
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0017.tex#L147
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0018.tex#L79
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0021.tex#L39
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0024.tex#L175
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0032.tex#L19
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0032.tex#L47
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0034.tex#L21
(下面四个不一定有问题, 只是不太符合我的语感.)
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0009.tex#L87
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0010.tex#L65
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0011.tex#L21
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0024.tex#L193
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0037.tex#L45
"搞的"→"搞得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0006.tex#L33
"过的"→"过得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0006.tex#L65
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0007.tex#L115
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0036.tex#L117
"引的"→"引得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0007.tex#L91
"扔的"→"扔得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0009.tex#L27
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0009.tex#L29
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0009.tex#L31
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0011.tex#L13
"肿的"→"肿得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0013.tex#L83
"爱的"→"爱得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0014.tex#L65
"好的"→"好得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0014.tex#L72
"长的"→"长得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0015.tex#L53
"打理的"→"打理得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0015.tex#L63
"怀才不遇的"→"怀才不遇得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0016.tex#L29
"靠的"→"靠得"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0017.tex#L23
"来的"→"来得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0025.tex#L9
"叠的"→"叠得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0025.tex#L17
"紧张的"→"紧张得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0026.tex#L111
"笑的"→"笑得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0026.tex#L113
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0026.tex#L113
"干的"→"干得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0028.tex#L17
"柔和的"→"柔和得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0032.tex#L29
"吃的"→"吃得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0032.tex#L37
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0035.tex#L39
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0035.tex#L39
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0035.tex#L41
"差的"→"差得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0032.tex#L77
"做的"→"做得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0032.tex#L113
"开的"→"开得"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0033.tex#L167

- "敲门"→"窍门"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0009.tex#L63

- "温柔和的"→"柔和的"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0017.tex#L59

- "仅"→"加"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0017.tex#L61

- "好象"→"好像"
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0017.tex#L117

- "得"→"的"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0033.tex#L81

- "报怨"→"抱怨"
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0034.tex#L123

**Comment by taroxd** [comment]
感谢报告，不过下面这几个并没有问题。另外……以后能不能用 pull request……

https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0024.tex#L80
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0035.tex#L41
https://github.com/taroxd/n8440fe/blob/cf07c07d3d6a4f3a1538fbe32250adc35f64ce14/0039.tex#L99
https://github.com/taroxd/n8440fe/blob/537a6edb8e89f08c225634a4784efb2c6ac86bf8/0017.tex#L61
