### ISSUE TITLE
61章的一些问题

### ISSUE THREAD

**Issue by BlueandwhiteXD** [taroxd/n8440fe#9]
本来想在群里艾特的，可能这时间已经睡下了...QQ的聊天记录往回翻又麻烦，就放这里了。没什么写issues的经验，就不引用了（其实是不清楚语法
0061.tex
51行 “我也吃不了那么准。”这个“吃不准”拆成这样可能有点难理解....（或许用“说不准”、“拿不准”会更好？）
143行 看描述应该是睡裙而不是睡袍吧

**Comment by taroxd** [comment]
事实上是 ネグリジェ，我没找到一个合适的中文词对应上。不过睡裙确实更好一些
